// Knowledge-graph adapter write paths — `createRecord` / `updateRecord` /
// `deleteRecord` / `linkRecords` / `unlinkRecords`, expressed over the graph's
// HTTP surface.
//
// This file used to reach into the store's write door in-process. It does not
// any more: every write here is a request, exactly as the reads next door are,
// which is what "the graph is just another optional adapter" has to mean if it
// means anything (D25). The last thing standing in the way was LLM property
// arbitration, which ran INSIDE the door's transaction through a callback this
// file supplied — unexpressible over a hop where one request is one
// transaction. D42 moved that behaviour to knowledge, where its declaration
// already lived, and the write path had nothing left that a hop could not
// carry.
//
// What the door still owns is everything it owned before — the `writable_by`
// gate, value coercion, evidence, change rows, edge idempotence,
// transactionality, and the mutation events it derives and enqueues. None of it
// is re-implemented on this side of the wire; the endpoints are the door. Since
// D43(a) it owns `node.summary` too: the summary is composed from knowledge's
// own tables and regenerated by the endpoints themselves, so there is no
// post-write enrichment call left here at all.
//
// Two things travel on every write for reasons worth stating:
//
//   - `changeSource: pipeline`. A movement-authored write reads as `pipeline`
//     in the change feed (D37f). Left to default, the same write would start
//     reading as `api` the moment it arrived over HTTP — a silent rewrite of
//     the feed's vocabulary that the move must not cause.
//   - the mutation context, verbatim. `suppress_self` answers itself from one
//     marker in it, and a bag stripped in transit makes every 2-way sync echo.

// Both of these are WIRE vocabulary — the generated enums the endpoints accept,
// not knowledge code. Imported from the generated types for the same reason the
// ids are: a spelling both sides agree on, checked by the compiler.
import ChangeSource from '../../../generated/kysely/knowledge/ChangeSource';
import { normalizeAdapterType } from '../../knowledge_pipeline/output_v3/linked_objects';
import { kgFetch, kgFetchOrNull, type KgCredentials, type WireOntology } from './kg_client';
import type { TeamId } from '../../../generated/kysely/core/Team';
import EvidenceType from '../../../generated/kysely/knowledge/EvidenceType';
import type { MutationContext, MutationSourceType } from '../mutation_context';
import type { FieldEvidence, ParentAssociation, ParentLink, Resource } from '../adapter';
import { persistKgResources } from './knowledge_graph_resources';
import { logger } from '../../logger';

/** Result of a KG write — the new node's external ID. */
export interface KgWriteResult {
  externalId: string;
}

/** What every write needs to reach the graph and read its model. */
interface WriteConnection {
  creds: KgCredentials;
  ontology: WireOntology;
}

interface PropertyWriteBody {
  propertyTypeId: string;
  value: unknown;
  description?: string;
}

/**
 * Create a node + properties + evidence in a single request — which is a single
 * transaction on the other side (K-25), edges and bridge included.
 */
export async function createKgRecord(input: {
  connection: WriteConnection;
  teamId: TeamId;
  recordType: string; // a knowledge.node_type ID
  fields: Record<string, unknown>; // keyed by property_type ID
  /** Per-field extraction provenance keyed by property_type ID — the quote
   *  that justified the value. Written onto each field's evidence row in the
   *  same transaction (3b §3.3). */
  evidence?: Record<string, FieldEvidence>;
  mutationContext: MutationContext;
  /**
   * Parent context for child actions authored against edge names — ONE
   * entry for an ordinary linked write, N for a tuple-path multi-parent
   * create (the record at the convergence of N edges). Every entry's edge
   * name resolves against the ontology and the connecting edge inserts
   * inside the SAME transaction as the node (structural atomicity). A name
   * that doesn't resolve throws — the author references an edge that no
   * longer exists, and a silent skip would hide the misconfig.
   */
  parentLinks?: ParentLink[];
  /**
   * When the create was triggered by an external source (webhook /
   * snapshot / poll), record the bridge: a `linked_object` row pointing the
   * new KG node at the source record, so the next inbound event for the same
   * record resolves back to this node rather than duplicating it.
   */
  bridgeToExternal?: {
    adapterType: string;
    recordId: string;
    recordType?: string;
  };
  /** Node-level resource provenance (`4d_resources.md`). */
  resources?: Resource[];
}): Promise<KgWriteResult> {
  const { creds, ontology } = input.connection;

  // Edge types are ontology facts, and the ontology is already in hand — this
  // used to be a query per parent link and is now a lookup per parent link.
  const edges = resolveParentEdges({
    ontology,
    childRecordType: input.recordType,
    parentLinks: input.parentLinks,
  }).map((edge) => ({
    edgeTypeId: edge.edgeTypeId,
    otherNodeId: edge.parentNodeId,
    direction: edge.parentIsSource ? ('in' as const) : ('out' as const),
  }));

  const { nodeId } = await kgFetch<{ nodeId: string }>(creds, {
    method: 'POST',
    path: '/nodes',
    body: {
      nodeTypeId: input.recordType,
      properties: fieldWrites(input.fields, input.evidence),
      edges,
      bridge: input.bridgeToExternal
        ? {
            adapterType: normalizeAdapterType(input.bridgeToExternal.adapterType),
            externalId: input.bridgeToExternal.recordId,
            externalObjectType: input.bridgeToExternal.recordType ?? null,
          }
        : undefined,
      ...writeProvenance(input.mutationContext),
    },
  });

  await persistKgResources({
    connection: input.connection,
    teamId: input.teamId,
    nodeId,
    resources: input.resources,
  });

  return { externalId: nodeId };
}

/**
 * Update properties on an existing KG node. Each field is set through the door,
 * which upserts the property row and appends a fresh evidence row — how
 * multiple sources contribute evidence without losing history.
 */
export async function updateKgRecord(input: {
  connection: WriteConnection;
  teamId: TeamId;
  externalId: string; // node ID
  recordType: string; // a knowledge.node_type ID
  fields: Record<string, unknown>;
  /** Per-field extraction provenance keyed by property_type ID (3b §3.3). */
  evidence?: Record<string, FieldEvidence>;
  mutationContext: MutationContext;
  /**
   * The parents this node must end up hanging off. Each connecting edge is
   * ASSERTED here (idempotently), so a matched node attaches exactly as a
   * freshly created one does — and an edge-anchored field write (W4-KG3)
   * lands on the edge that assert just answered with.
   */
  parentLinks?: ParentLink[];
  /** Node-level resource provenance (`4d_resources.md`). */
  resources?: Resource[];
}): Promise<{ ok: true; association: ParentAssociation } | { notFound: true }> {
  const { creds, ontology } = input.connection;
  const nodeId = input.externalId;

  const writes = fieldWrites(input.fields, input.evidence);
  const edgeTypeByProperty = edgeAnchors(ontology, writes);
  const nodeAnchored = writes.filter((w) => !edgeTypeByProperty.get(w.propertyTypeId));
  const edgeAnchored = writes.filter((w) => edgeTypeByProperty.get(w.propertyTypeId));

  // NOT-FOUND contract (3b): an update is a write BY id. If the node was
  // deleted (e.g. externally, between events), report it so the engine's bind
  // self-heal can re-mint rather than failing on an FK violation. The 404 the
  // node endpoint returns is that same contract, transported.
  //
  // With no node-anchored property to set — a matched node reached with
  // nothing of its own to change (a parent-only attach, or a resources-only
  // write) — the PATCH would carry an empty property list and append nothing.
  // The GET stands in: same 404, no write.
  const updated =
    nodeAnchored.length > 0
      ? await kgFetchOrNull<{ nodeId: string }>(creds, {
          method: 'PATCH',
          path: `/nodes/${nodeId}`,
          body: { properties: nodeAnchored, ...writeProvenance(input.mutationContext) },
        })
      : await kgFetchOrNull<{ nodeId: string }>(creds, {
          method: 'GET',
          path: `/nodes/${nodeId}`,
        });
  if (updated === null) return { notFound: true };

  // MATCHING IS NOT ASSOCIATING. A matched node still has to end up hanging
  // off the parent the write names, and until now nothing here made that
  // happen: the parent links were consulted only to FIND an edge an
  // edge-anchored field could be written on, so `write parent-[:edge]-> { … }`
  // against an existing node created no edge at all.
  //
  // The edge assert is the same door `linkKgRecords` uses and the same
  // resolution the create path uses, so the two spellings of "attach this
  // child" cannot drift; the door is idempotent, so a re-run makes nothing.
  // It also answers each edge's own id, which is exactly what an edge-anchored
  // field write needs — so the separate "find the existing edges" read is gone.
  const edgeIdByType = new Map<string, string>();
  let association: ParentAssociation = 'none';
  const parentEdges = resolveParentEdges({
    ontology,
    childRecordType: input.recordType,
    parentLinks: input.parentLinks,
  });
  if (parentEdges.length > 0) association = 'already';
  for (const edge of parentEdges) {
    const { edgeId, created } = await kgFetch<{ edgeId: string; created: boolean }>(creds, {
      method: 'POST',
      path: '/edges',
      body: {
        edgeTypeId: edge.edgeTypeId,
        ...edgeEnds(!edge.parentIsSource, nodeId, edge.parentNodeId),
        ...writeProvenance(input.mutationContext),
      },
    });
    edgeIdByType.set(edge.edgeTypeId, edgeId);
    if (created) association = 'made';
  }

  for (const write of edgeAnchored) {
    const edgeTypeId = edgeTypeByProperty.get(write.propertyTypeId)!;
    const edgeId = edgeIdByType.get(edgeTypeId);
    if (!edgeId) {
      logger.debug('[KG updateKgRecord] edge-anchored field without a matching parent-link edge — skipping', {
        propertyTypeId: write.propertyTypeId,
        edgeTypeId,
        parentLinkEdgeTypes: [...edgeIdByType.keys()],
      });
      continue;
    }
    await kgFetch(creds, {
      method: 'PATCH',
      path: `/edges/${edgeId}`,
      body: { properties: [write], ...writeProvenance(input.mutationContext) },
    });
  }

  await persistKgResources({
    connection: input.connection,
    teamId: input.teamId,
    nodeId,
    resources: input.resources,
  });

  return { ok: true, association };
}

/**
 * Edge-only assertion between two EXISTING nodes — the KG adapter's
 * `linkRecords` implementation (the movement language's standalone
 * `edge a -[:e]-> b`). The edge name resolves by the same outbound/inbound
 * ontology matching the parent-link machinery uses, from the from-side's
 * perspective; the door's link is idempotent (D37e), so re-asserting an
 * existing edge is a no-op.
 */
export async function linkKgRecords(input: {
  connection: WriteConnection;
  from: { recordType: string; externalId: string };
  edgeName: string;
  to: { recordType: string; externalId: string };
  mutationContext: MutationContext;
}): Promise<{ created: boolean }> {
  const resolved = resolveParentLinkEdgeType({
    ontology: input.connection.ontology,
    parentRecordType: input.from.recordType,
    childRecordType: input.to.recordType,
    edgeName: input.edgeName,
  });
  const { created } = await kgFetch<{ edgeId: string; created: boolean }>(
    input.connection.creds,
    {
      method: 'POST',
      path: '/edges',
      body: {
        edgeTypeId: resolved.edgeTypeId,
        ...edgeEnds(resolved.parentIsSource, input.from.externalId, input.to.externalId),
        ...writeProvenance(input.mutationContext),
      },
    },
  );
  return { created };
}

/**
 * Sever an edge between two existing nodes — the exact inverse of
 * `linkKgRecords`, idempotent in the same way.
 */
export async function unlinkKgRecords(input: {
  connection: WriteConnection;
  from: { recordType: string; externalId: string };
  edgeName: string;
  to: { recordType: string; externalId: string };
  mutationContext: MutationContext;
}): Promise<{ removed: boolean }> {
  const resolved = resolveParentLinkEdgeType({
    ontology: input.connection.ontology,
    parentRecordType: input.from.recordType,
    childRecordType: input.to.recordType,
    edgeName: input.edgeName,
  });
  const { removed } = await kgFetch<{ removed: boolean }>(input.connection.creds, {
    method: 'DELETE',
    path: '/edges',
    body: {
      edgeTypeId: resolved.edgeTypeId,
      ...edgeEnds(resolved.parentIsSource, input.from.externalId, input.to.externalId),
      ...writeProvenance(input.mutationContext),
    },
  });
  return { removed };
}

/**
 * Hard-delete a node — the KG adapter's `deleteRecord` implementation. The FK
 * cascades take properties, edges, evidence, bridges and resource links with
 * it. Deleting a node that no longer exists is an idempotent no-op.
 */
export async function deleteKgRecord(input: {
  connection: WriteConnection;
  /** Resolved by the caller, which is where an unknown type name fails loud —
   *  the delete itself needs only the node id. */
  recordType: string; // a knowledge.node_type ID
  externalId: string; // the node id
  mutationContext: MutationContext;
}): Promise<{ removed: boolean }> {
  const result = await kgFetchOrNull<{ removed: boolean }>(input.connection.creds, {
    method: 'DELETE',
    path: `/nodes/${input.externalId}`,
    body: writeProvenance(input.mutationContext),
  });
  return { removed: result?.removed ?? false };
}

// ── Adapter-side plumbing ──────────────────────────────────────────────────

/**
 * The write's provenance, in the wire's vocabulary. `changeSource` is stated
 * rather than defaulted — see the file header.
 */
function writeProvenance(mutationContext: MutationContext) {
  return {
    evidence: {
      type: mapEvidenceType(mutationContext.source.type),
      description: describeEvidence(mutationContext),
    },
    changeSource: ChangeSource.pipeline,
    mutationContext,
  };
}

function fieldWrites(
  fields: Record<string, unknown>,
  evidence: Record<string, FieldEvidence> | undefined,
): PropertyWriteBody[] {
  return Object.entries(fields)
    .filter(([, value]) => value !== undefined)
    .map(([propertyTypeId, value]) => ({
      propertyTypeId,
      value,
      ...(evidence?.[propertyTypeId]?.quote === undefined
        ? {}
        : { description: evidence[propertyTypeId].quote }),
    }));
}

/** Which of these property types are edge-anchored (W4-KG3), and on what edge
 *  type — read off the published model rather than queried per write. */
function edgeAnchors(ontology: WireOntology, writes: PropertyWriteBody[]): Map<string, string> {
  const anchors = new Map<string, string>();
  if (writes.length === 0) return anchors;
  const wanted = new Set(writes.map((w) => w.propertyTypeId));
  for (const pt of ontology.propertyTypes) {
    if (wanted.has(pt.id) && pt.edgeTypeId) anchors.set(pt.id, pt.edgeTypeId);
  }
  return anchors;
}

function edgeEnds(
  fromIsSource: boolean,
  fromId: string,
  toId: string,
): { sourceNodeId: string; targetNodeId: string } {
  return fromIsSource
    ? { sourceNodeId: fromId, targetNodeId: toId }
    : { sourceNodeId: toId, targetNodeId: fromId };
}

/**
 * Every parent link a write carries, resolved to the edge that connects it.
 * ONE resolution shared by the create path (which inserts these edges inside
 * the node's own transaction) and the update path (which asserts them against
 * a node that already exists), so a matched child and a fresh one cannot come
 * to mean different things.
 */
function resolveParentEdges(input: {
  ontology: WireOntology;
  childRecordType: string;
  parentLinks: ParentLink[] | undefined;
}): Array<{ edgeTypeId: string; parentIsSource: boolean; parentNodeId: string }> {
  return (input.parentLinks ?? []).map((parentLink) => ({
    ...resolveParentLinkEdgeType({
      ontology: input.ontology,
      parentRecordType: parentLink.recordType,
      childRecordType: input.childRecordType,
      edgeName: parentLink.edgeName,
    }),
    parentNodeId: parentLink.externalId,
  }));
}

/**
 * Resolve the `edge_type` between a parent and child node type by the
 * author-facing edge name: outbound when the parent is the edge type's source,
 * inbound when the parent is its target. Returns which end the parent sits on
 * so the caller can pick source/target.
 */
function resolveParentLinkEdgeType(input: {
  ontology: WireOntology;
  parentRecordType: string;
  childRecordType: string;
  edgeName: string;
}): { edgeTypeId: string; parentIsSource: boolean } {
  const outbound = input.ontology.edgeTypes.find(
    (e) =>
      e.sourceNodeTypeId === input.parentRecordType &&
      e.targetNodeTypeId === input.childRecordType &&
      e.outboundName === input.edgeName,
  );
  if (outbound) return { edgeTypeId: outbound.id, parentIsSource: true };

  const inbound = input.ontology.edgeTypes.find(
    (e) =>
      e.sourceNodeTypeId === input.childRecordType &&
      e.targetNodeTypeId === input.parentRecordType &&
      e.inboundName === input.edgeName,
  );
  if (inbound) return { edgeTypeId: inbound.id, parentIsSource: false };

  throw new Error(
    `KG adapter: no edge type matches "${input.edgeName}" between parent type ${input.parentRecordType} and child type ${input.childRecordType}. Either the ontology has changed since the TG was authored, or the edge name was mistyped — re-pick the relationship in the editor.`,
  );
}

/**
 * Map MutationContext.source.type to the evidence_type enum — the gate's
 * currency. The structured `mutation_context` jsonb carries the full
 * provenance; this is the coarse classification the ontology reasons about.
 */
function mapEvidenceType(sourceType: MutationSourceType): EvidenceType {
  switch (sourceType) {
    case 'structured_input':
      return EvidenceType.input_mapping;
    case 'extraction':
      return EvidenceType.extraction;
    case 'user_edit':
      return EvidenceType.user_edit;
    case 'api':
    case 'agent':
      return EvidenceType.user_edit; // closest fit; structured context has the real source
  }
}

function describeEvidence(ctx: MutationContext): string {
  const parts: string[] = [];
  if (ctx.source.translationGraphId) parts.push(`tg=${ctx.source.translationGraphId}`);
  if (ctx.source.translationGraphNodeId) parts.push(`node=${ctx.source.translationGraphNodeId}`);
  if (ctx.source.adapterType) parts.push(`adapter=${ctx.source.adapterType}`);
  if (ctx.source.pipelineInputId) parts.push(`input=${ctx.source.pipelineInputId}`);
  if (parts.length === 0) return `source=${ctx.source.type}`;
  return parts.join(' ');
}

export type { WriteConnection };
