const topVcs: string[] = [
  'Index Ventures',
  'LocalGlobe',
  'Point Nine',
  'Global Founders Capital',
  'Kima Ventures',
  'DST Global',
  'HV Capital',
  'Partech',
  'Seedcamp',
  'Seedcamp V LP',
  'Creandum',
  'Baillie Gifford',
  'Cherry Ventures',
  'Speedinvest',
  'Eight Roads Ventures',
  'Lakestar',
  'Balderton Capital',
  'Balderton',
  'Entrée Capital',
  'Eurazeo',
  'ACE and Company',
  'Mangrove Capital Partners',
  'Northzone',
  'Target Global',
  'Atomico',
  'Start Fund',
  'Picus Capital',
  'Alven',
  'Kinnevik',
  'Bpifrance',
  'Episode 1 Ventures',
  '83North',
  'Passion Capital',
  'Prosus',
  'StartCaps Ventures',
  'Anthemis Group',
  'White Star Capital',
  'IRIS',
  'b2venture',
  'Sofinnova Partners',
  'Redalpine',
  'Greyhound Capital',
  'Fondation FIT',
  'Octopus Ventures',
  'Acton Capital',
  'Heartcore Capital',
  'Sunstone Capital',
  'SGH Capital',
  'Elaia Partners',
  'Hexa',
  'eFounders',
  'Janus Henderson Investors',
  'Earlybird Venture Capital',
  'MMC Ventures',
  'Blue Horizon Corporation',
  'Lifeline Ventures',
  'Felix Capital',
  'Aglaé Ventures',
  'GP Bullhound',
  'Lightrock',
  'Atlantic Labs',
  'DN Capital',
  'Market One Capital',
  'Sherpa Capital',
  'Project A',
];

export { topVcs };
