const THEMES = [
  "Crypto / Web3",
  "SaaS",
  "B2B",
  "Fintech",
  "Developer Tools",
  "Artificial Intelligence",
  "Marketplace",
  "E-commerce",
  "Machine Learning",
  "AI",
  "Education",
  "Analytics",
  "Climate",
  "Generative AI",
  "Consumer",
  "Healthcare",
  "Payments",
  "Open Source",
  "API",
  "Health Tech",
  "Productivity",
  "Biotech",
  "Consumer Health Services",
  "Logistics",
  "Hardware",
  "Enterprise",
  "Data Engineering",
  "Proptech",
  "Digital Health",
  "Gaming",
  "Sales",
  "Social",
  "Security",
  "Community",
  "Medical Devices",
  "Hard Tech",
  "Video",
  "Real Estate",
  "Computer Vision",
  "HR Tech",
  "Insurance",
  "Recruiting",
  "Robotics",
  "Delivery",
  "Neobank",
  "Supply Chain",
  "Design Tools",
  "eLearning",
  "Construction",
  "Food Tech",
  "Mental Health Tech",
  "Retail",
  "Investing",
  "Collaboration",
  "Marketing",
  "IoT",
  "Messaging",
  "Entertainment",
  "Travel",
  "Subscriptions",
  "Finance",
  "Media",
  "Infrastructure",
  "Deep Learning",
  "Enterprise Software",
  "LegalTech",
  "Telemedicine",
  "Diagnostics",
  "Therapeutics",
  "DevSecOps",
  "Grocery",
  "No-code",
  "Transportation",
  "Automation",
  "Compliance",
  "Creator Economy",
  "NLP",
  "ClimateTech",
  "AIOps",
  "Drug discovery",
  "Genomics",
  "GovTech",
  "AI Assistant",
  "AI-powered Drug Discovery",
  "Nonprofit",
  "Agriculture",
  "Banking as a Service",
  "AI-Enhanced Learning",
  "Advertising",
  "DevOps",
  "Electric Vehicles",
  "Energy",
  "Health & Wellness",
  "Manufacturing",
  "FinOps",
  "Food & Beverage",
  "Telehealth",
  "Cloud Computing",
  "Cybersecurity",
  "Documents",
  "Latin America",
  "Synthetic Biology",
  "Email",
  "Workflow Automation",
  "Augmented Reality",
  "Drones",
  "Fashion",
  "Sales Enablement",
  "Social Media",
  "Customer Success",
  "DeFi",
  "Human Resources",
  "Music",
  "Remote Work",
  "Robotic Process Automation",
  "Satellites",
  "Social Network",
  "Identity",
  "Privacy",
  "Sustainability",
  "CRM",
  "Customer Support",
  "Health Insurance",
  "Housing",
  "Retail Tech",
  "Space Exploration",
  "Sports Tech",
  "Telecommunications",
  "Oncology",
  "SMB",
  "Solar Power",
  "Big Data",
  "Customer Service",
  "Design",
  "Neurotechnology",
  "Renewable Energy",
  "Virtual Reality",
  "Carbon Capture and Removal",
  "Data Science",
  "Fitness",
  "Healthcare IT",
  "Operations",
  "Airplanes",
  "Consumer Finance",
  "Ghost Kitchens",
  "Kubernetes",
  "NFT",
  "Payroll",
  "Team Collaboration",
  "Warehouse Management Tech",
  "Women's Health",
  "3D Printing",
  "Aerospace",
  "Autonomous Trucking",
  "Data Visualization",
  "Energy Storage",
  "Food Service Robots & Machines",
  "Automotive",
  "Beauty",
  "Crowdfunding",
  "Databases",
  "Gene Therapy",
  "Legal",
  "Lending",
  "Nanotechnology",
  "Regtech",
  "Sustainable Fashion",
  "Autonomous Delivery",
  "Chatbot",
  "Fertility Tech",
  "Kids",
  "Scheduling",
  "Sleep Tech",
  "Assistive Tech",
  "Calendar",
  "Edtech",
  "Femtech",
  "Metaverse",
  "Mobility",
  "Personalization",
  "Primary Care",
  "Remote",
  "Restaurant Tech",
  "Cannabis",
  "Civic Tech",
  "Dating",
  "Furniture",
  "Geographic Information System",
  "Monitoring",
  "Podcasts",
  "Procurement",
  "Web Development",
  "Air Taxis",
  "Auto Commerce",
  "Biometrics",
  "Cellular Agriculture",
  "Commercial Space Launch",
  "Conversational AI",
  "Digital Freight Brokerage",
  "Live",
  "ML",
  "APIs",
  "Anti-Aging",
  "Biotechnology",
  "COVID-19",
  "Cashierless Checkout",
  "Cloud Gaming",
  "Cloud Workload Protection",
  "Consumer Products",
  "DAO",
  "Emerging Markets",
  "Food",
  "Microfluidics",
  "Nanomedicine",
  "Next-gen Network Security",
  "Remittances",
  "Search",
  "Smart Clothing",
  "Smart Home Assistants",
  "Advanced Materials",
  "Airlines",
  "Apparel",
  "Billing",
  "Careers",
  "Cell Therapy",
  "Cryptocurrency",
  "Diversity & Inclusion",
  "Drug Delivery",
  "Fraud Detection",
  "GraphQL",
  "Hydrogen Energy",
  "Income Share Agreements",
  "Industrial",
  "Industrial Workplace Safety",
  "Market Research",
  "Medical Robotics",
  "Nanosensors",
  "Recommendation System",
  "SMS",
  "Self-Driving Vehicles",
  "Trust & Safety",
  "Vertical Farming",
  "Alternative Battery Tech",
  "Bioplastic",
  "Crowdsourcing",
  "Cultivated Meat",
  "Cultured Meat",
  "Electronics",
  "Fraud Prevention",
  "Genetic Engineering",
  "Immigration",
  "Indoor Mapping",
  "Mental Health",
  "Microinsurance",
  "Note-taking",
  "Pediatrics",
  "Quantum Computing",
  "Reinforcement Learning",
  "SEO",
  "Security Orchestration, Automation and Response (SOAR)",
  "Speech Recognition",
  "Talent Acquisition",
  "Time Series",
  "Trading",
  "Unmanned Vehicle",
  "eSports",
  "AR",
  "Art Trading Platforms",
  "Blockchain",
  "Booking",
  "CRISPR",
  "Chat",
  "Chatbots",
  "Coding Bootcamps",
  "Conversational Banking",
  "Culture",
  "Customization",
  "Cyber Insurance",
  "Data Labeling",
  "Dental",
  "Election Tech",
  "Feedback",
  "Gardening",
  "Home Automation",
  "Home Services",
  "International",
  "Location-based",
  "Maritime",
  "Mining",
  "Navigation",
  "Networks",
  "Notifications",
  "Plant-based Meat",
  "Psychedelics",
  "Radar",
  "Referrals",
  "Reviews",
  "Ridesharing",
  "Rocketry",
  "Small Modular Reactors",
  "Stocks",
  "Sustainable Agriculture",
  "Sustainable Tourism",
  "Ticketing",
  "VR Health",
  "Weather",
  "3D Printed Foods",
  "Alternative Fuels",
  "Batteryless IoT Sensors",
  "Call Center",
  "Clean Meat",
  "Computational Storage",
  "Cryogenics",
  "Cryptography",
  "Deepfake Detection",
  "Edge Computing Semiconductors",
  "Fundraising",
  "Fusion Energy",
  "Investment",
  "IoT Security",
  "Lab-on-a-chip",
  "Robotic Surgery",
  "Semiconductors",
  "Skincare",
  "Smart Locks",
  "web3",
  "Employee Benefits",
  "Open Banking",
] as const;

export type Theme = (typeof THEMES)[number];

export { THEMES };
