CREATE SCHEMA IF NOT EXISTS _migrations;

CREATE TABLE IF NOT EXISTS _migrations.migrations (
  id SERIAL PRIMARY KEY,
  version VARCHAR(255) NOT NULL,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);