// On the Google route the DALL-E fallback behind image generation must not
// exist: there is no OpenAI account for it to belong to, so reaching for one
// would fail on a deliberately absent key instead of on the real problem.

const imagesGenerate = jest.fn();
const openAiCtor = jest.fn();
jest.mock('openai', () => ({
  __esModule: true,
  default: jest.fn().mockImplementation((options: unknown) => {
    openAiCtor(options);
    return { images: { generate: imagesGenerate } };
  }),
}));

let route: 'direct' | 'google' = 'direct';
jest.mock('../model_route', () => ({ openAiRoute: () => route }));

jest.mock('../../adapters/registry', () => ({ services: {} }));
jest.mock('../../services/logger', () => ({ logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn() } }));

import { generateImage } from '../file_generation';

const SAVED_ENV = { ...process.env };

beforeEach(() => {
  route = 'direct';
  // No Google service account: the branch that would otherwise reach for DALL-E.
  delete process.env.GOOGLE_PRIVATE_KEY;
  delete process.env.GOOGLE_CLIENT_EMAIL;
  delete process.env.GOOGLE_PROJECT_ID;
  imagesGenerate.mockReset().mockResolvedValue({ data: [{ b64_json: 'AAAA' }] });
  openAiCtor.mockClear();
});

afterAll(() => {
  process.env = SAVED_ENV;
});

it('still falls back to DALL-E on the direct route', async () => {
  // It gets as far as OpenAI and then fails on storage, which is not wired here
  // — what matters is that the OpenAI client was built and asked.
  await expect(generateImage({ prompt: 'a leaf', title: 't' })).rejects.toThrow();
  expect(imagesGenerate).toHaveBeenCalledWith(expect.objectContaining({ model: 'dall-e-3' }));
});

it('names the missing Google credentials on the google route, and builds no OpenAI client', async () => {
  route = 'google';
  await expect(generateImage({ prompt: 'a leaf', title: 't' })).rejects.toThrow(
    /images are generated by Gemini.*GOOGLE_PRIVATE_KEY/s,
  );
  expect(openAiCtor).not.toHaveBeenCalled();
  expect(imagesGenerate).not.toHaveBeenCalled();
});
