import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  ignore: [
    'src/generated/**/*.ts|src/prisma/types.ts', // autogenerated, we don't need to use every export
    'src/services/document_sources/tome.ts', // not enabling tome support yet
    'src/lib/portfolio/secondaries.ts', // hooking this up soon
    'build/**',
  ],
  entry: [
    'src/server.ts', // entrypoint for server
    'src/interfaces/cli/cli.ts', // entrypoint for CLI
    'src/runPipeline.ts', // entrypoint for pipeline
    'src/interfaces/cli/commands/*.ts', // dynamically imported from src/interfaces/cli/cli.ts
    'src/test/globalSetup.ts', // used by Jest, referenced in jest-integration.config.ts
    'src/test/jest-integration.config.ts', // used by Jest, referenced in package.json
    'src/test/jest-unit.config.ts', // used by Jest, referenced in package.json
    'src/interfaces/trpc/index.ts', // entrypoint for trpc types for UI
    'src/lib/utils/email_providers.ts', // standalone value?
    'src/lib/cache.ts', // standalone value?
  ],
  ignoreBinaries: ['diff', 'make', 'sed'],
  ignoreDependencies: [
    'prisma-kysely', // vestigial (schema.prisma retired); pending dep removal
    '#shared', // shared is a monorepo package, doesn't show up as used for some reason
    '@types/redis-info', // is needed in prod build step, will fall over otherwise
    '@swc-node/register', // used in dev to compile faster
    'ts-jest', // used in jest configs
    '@langchain/core', // required peer dependency for @langchain/openai
  ],
};

export default config; // eslint-disable-line local-rules/bottom-exports
